name: Build latest
on: [push]

concurrency:
  group: ${{ github.ref }}-latest
  cancel-in-progress: true

jobs:
  build-mono:
    if: github.ref_name == github.event.repository.default_branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile PattyKaki
        shell: bash
        id: compile
        run: |
          msbuild PattyKaki.sln /p:Configuration=Release
          cp -R bin/Release
          rm bin/Release/PattyKaki.exe bin/Release/PattyKaki_.pdb
          msbuild PK/PattyKaki.csproj /p:Configuration=Release

      - uses: ./.github/actions/notify_failure
        if: ${{ always() && steps.compile.outcome == 'failure' }}
        with:
          NOTIFY_MESSAGE: 'Failed to compile PattyKaki! <@804431499867717713>'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
          
      - uses: ./.github/actions/notify_success
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'bin/Release'
          DEST_NAME: 'PattyKaki'
          NOTIFY_MESSAGE: 'Successfully compiled PattyKaki.'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'