name: Build PK
on:
  push:
  workflow_dispatch:
  schedule:
    # Every day at 12am
    - cron: '0 0 * * *'

concurrency:
  group: ${{ github.ref }}-latest
  cancel-in-progress: true

jobs:
  Build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Compile PattyKaki
        shell: bash
        id: compile
        run: |
          msbuild PattyKaki.sln /p:Configuration=Release
          rm bin/PattyKaki.exe bin/PattyKaki.pdb
          msbuild PK/PattyKaki.csproj /p:Configuration=Release

      - uses: ./.github/actions/notify_failure
        if: ${{ always() && steps.compile.outcome == 'failure' }}
        with:
          NOTIFY_MESSAGE: 'Failed to compile PattyKaki! <@804431499867717713>'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
          
      - uses: ./.github/actions/notify_success
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'bin'
          DEST_NAME: 'PattyKaki'
          NOTIFY_MESSAGE: 'Successfully compiled PattyKaki.'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'