name: Build MAX
on:
  push:
  workflow_dispatch:
  schedule:
    # Every day at 12am
    - cron: '0 0 * * *'

concurrency:
  group: ${{ github.ref }}-latest
  cancel-in-progress: true

jobs:
  Build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Compile MAX
        shell: bash
        id: compile
        run: |
          msbuild MAX.sln /p:Configuration=Release
          rm bin/MAX.exe bin/MAX.pdb
          msbuild MAX/MAX.csproj /p:Configuration=Release

      - uses: ./.github/actions/notify_failure
        if: ${{ always() && steps.compile.outcome == 'failure' }}
        with:
          NOTIFY_MESSAGE: 'Failed to compile MAX! <@999409543001931788>'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
          
      - uses: ./.github/actions/notify_success
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'bin'
          DEST_NAME: 'MAX'
          NOTIFY_MESSAGE: 'Successfully compiled MAX.'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'