name: Build PK
on: [push]

concurrency:
  group: ${{ github.ref }}-latest
  cancel-in-progress: true

jobs:
  Build:
    if: github.ref_name == github.event.repository.default_branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile PattyKaki
        shell: bash
        id: compile
        run: |
          msbuild PattyKaki.sln /p:Configuration=Release
          rm bin/PattyKaki.exe bin/PattyKaki.pdb
          msbuild PK/PattyKaki.csproj /p:Configuration=Release

      - uses: ./.github/actions/notify_failure
        if: ${{ always() && steps.compile.outcome == 'failure' }}
        with:
          NOTIFY_MESSAGE: 'Failed to compile PattyKaki! <@804431499867717713>'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
          
      - uses: ./.github/actions/notify_success
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'bin'
          DEST_NAME: 'PattyKaki'
          NOTIFY_MESSAGE: 'Successfully compiled PattyKaki.'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'

      - uses: ./.github/actions/notify_failure
        if: ${{ always() && steps.compile.outcome == 'failure' }}
        with:
          NOTIFY_MESSAGE: 'Failed to compile PattyKaki! <@1033483516622675968>'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL2 }}'
          
      - uses: ./.github/actions/notify_success
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'bin'
          DEST_NAME: 'PattyKaki'
          NOTIFY_MESSAGE: 'Successfully compiled PattyKaki.'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL2 }}'

      - uses: ./.github/actions/notify_failure
        if: ${{ always() && steps.compile.outcome == 'failure' }}
        with:
          NOTIFY_MESSAGE: 'Failed to compile PattyKaki! <@999409543001931788>'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL3 }}'
          
      - uses: ./.github/actions/notify_success
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'bin'
          DEST_NAME: 'PattyKaki'
          NOTIFY_MESSAGE: 'Successfully compiled PattyKaki.'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL3 }}'

      - uses: ./.github/actions/notify_failure
        if: ${{ always() && steps.compile.outcome == 'failure' }}
        with:
          NOTIFY_MESSAGE: 'Failed to compile PattyKaki! <@999409543001931788>'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL4 }}'
          
      - uses: ./.github/actions/notify_success
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'bin'
          DEST_NAME: 'PattyKaki'
          NOTIFY_MESSAGE: 'Successfully compiled PattyKaki.'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL4 }}'


      - uses: ./.github/actions/notify_failure
        if: ${{ always() && steps.compile.outcome == 'failure' }}
        with:
          NOTIFY_MESSAGE: 'Failed to compile PattyKaki! <@999409543001931788>'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL5 }}'
          
      - uses: ./.github/actions/notify_success
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'bin'
          DEST_NAME: 'PattyKaki'
          NOTIFY_MESSAGE: 'Successfully compiled PattyKaki.'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL5 }}'