name: Build dotnet
# trigger via either push to selected branches or on manual run
on:
  push:
  workflow_dispatch:
  schedule:
    # Every day at 12am
    - cron: '0 0 * * *'
concurrency:
  group: ${{ github.ref }}-dotnet
  cancel-in-progress: true

jobs:
#============================================
# ============== .NET 8.0 BUILD =============
# ===========================================
  build-dotnet8:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore MAX/MAX_dotnet8.csproj
      - name: Build
        id: compile
        run: |
          dotnet build MAX/MAX_dotnet8.csproj --no-restore
        
      - uses: ./.github/actions/notify_failure
        if: ${{ always() && steps.compile.outcome == 'failure' }}
        with:
          NOTIFY_MESSAGE: 'Failed to compile MAX dotnet build! <@999409543001931788>'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
          
      - uses: ./.github/actions/notify_success
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'MAX/bin/Debug/net8.0'
          DEST_NAME: 'MAX-net8.0'
          NOTIFY_MESSAGE: 'Successfully compiled MAX dotnet build.'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'